// <auto-generated />
using System;
using MagicButton.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicButton.Migrations
{
    [DbContext(typeof(MagicDbContext))]
    [Migration("20251022210749_removeDefaults")]
    partial class removeDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MagicButton.Data.Models.ActionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeviceConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetriesBaseDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RetriesJitter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetriesMaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigId", "Kind")
                        .IsUnique();

                    b.ToTable("action_config", (string)null);
                });

            modelBuilder.Entity("MagicButton.Data.Models.ButtonPress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActionConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DeviceConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LedDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LedId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LedPattern")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PressedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Queued")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBodySnippet")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Simulated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TransportError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActionConfigId");

                    b.HasIndex("DeviceConfigId");

                    b.HasIndex("LedId");

                    b.HasIndex("PressedAtUtc");

                    b.HasIndex("DeviceId", "PressedAtUtc");

                    b.ToTable("button_press", (string)null);
                });

            modelBuilder.Entity("MagicButton.Data.Models.DeviceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ButtonPin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ButtonPullUp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DebounceMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoublePressWindowMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongPressThresholdMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetriesBaseDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetriesMaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("device_config", (string)null);
                });

            modelBuilder.Entity("MagicButton.Data.Models.Led", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ActiveLow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Pin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigId", "Pin")
                        .IsUnique();

                    b.ToTable("led", (string)null);
                });

            modelBuilder.Entity("MagicButton.Data.Models.ResponseMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodeStart")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceConfigId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2000);

                    b.Property<Guid>("LedId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pattern")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TransportError")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigId");

                    b.HasIndex("LedId");

                    b.HasIndex("DeviceConfigId", "TransportError", "CodeStart", "CodeEnd", "Priority");

                    b.ToTable("response_mapping", (string)null);
                });

            modelBuilder.Entity("MagicButton.Data.Models.ActionConfig", b =>
                {
                    b.HasOne("MagicButton.Data.Models.DeviceConfig", "DeviceConfig")
                        .WithMany("Actions")
                        .HasForeignKey("DeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfig");
                });

            modelBuilder.Entity("MagicButton.Data.Models.ButtonPress", b =>
                {
                    b.HasOne("MagicButton.Data.Models.ActionConfig", "ActionConfig")
                        .WithMany()
                        .HasForeignKey("ActionConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MagicButton.Data.Models.DeviceConfig", "DeviceConfig")
                        .WithMany("Presses")
                        .HasForeignKey("DeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicButton.Data.Models.Led", "Led")
                        .WithMany()
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActionConfig");

                    b.Navigation("DeviceConfig");

                    b.Navigation("Led");
                });

            modelBuilder.Entity("MagicButton.Data.Models.Led", b =>
                {
                    b.HasOne("MagicButton.Data.Models.DeviceConfig", "DeviceConfig")
                        .WithMany("Leds")
                        .HasForeignKey("DeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfig");
                });

            modelBuilder.Entity("MagicButton.Data.Models.ResponseMapping", b =>
                {
                    b.HasOne("MagicButton.Data.Models.DeviceConfig", "DeviceConfig")
                        .WithMany("ResponseMappings")
                        .HasForeignKey("DeviceConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicButton.Data.Models.Led", "Led")
                        .WithMany()
                        .HasForeignKey("LedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceConfig");

                    b.Navigation("Led");
                });

            modelBuilder.Entity("MagicButton.Data.Models.DeviceConfig", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Leds");

                    b.Navigation("Presses");

                    b.Navigation("ResponseMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
